Update README.md
Grunt v0.4.1 complains with v0.10.13 complains about the `-` character in the config entry for cache-bust:


         cache-bust: {
              ^
     Loading "Gruntfile.js" tasks...ERROR
     >> SyntaxError: Unexpected token -
     Warning: Task "build" not found. Use --force to continue.

     Aborted due to warnings.